config/routes.rb
Rails.application.routes.draw do
  # Semi-static page routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/help', to: 'home#help', as: :help
  get 'home/faq', to: 'home#faq', as: :faq
  get 'home/add_company', to: 'home#add_company', as: :add_company
  get 'home/search', to: 'home#search', as: :search

  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # You can have the root of your site routed with 'root'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    # Relationship
    has_many :tcs

    # Scope
    scope :alphabetical, -> { order('name') }

    # Validation
    validates_presence_of :name, :description, :url, :logo, :crunchbase_url
    validates_uniqueness_of :url, case_sensitive: false

end

app/models/tc.rb
class Tc < ApplicationRecord
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: :show

  # GET /companies or /companies.json
  def index
    @companies = Company.alphabetical.all
  end

  # GET /companies/1 or /companies/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end

    def about
    end

    def help
    end

    def faq
    end

    def add_company
    end

    def search
        redirect_back(fallback_location: home_path) if params[:query].blank?
        @query = params[:query]
        @companies = Owner.search(@query)
    end
end

app/controllers/t_cs_controller.rb
class TCsController < ApplicationController
  before_action :set_tc, only: %i[ show edit update destroy ]

  # GET /tcs or /tcs.json
  def index
    @tcs = Tc.all
  end

  # GET /tcs/1 or /tcs/1.json
  def show
  end

  # GET /tcs/new
  def new
    @tc = Tc.new
  end

  # GET /tcs/1/edit
  def edit
  end

  # POST /tcs or /tcs.json
  def create
    @tc = Tc.new(tc_params)

    respond_to do |format|
      if @tc.save
        format.html { redirect_to @tc, notice: "Tc was successfully created." }
        format.json { render :show, status: :created, location: @tc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tcs/1 or /tcs/1.json
  def update
    respond_to do |format|
      if @tc.update(tc_params)
        format.html { redirect_to @tc, notice: "Tc was successfully updated." }
        format.json { render :show, status: :ok, location: @tc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tcs/1 or /tcs/1.json
  def destroy
    @tc.destroy
    respond_to do |format|
      format.html { redirect_to tcs_url, notice: "Tc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tc
      @tc = Tc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tc_params
      params.require(:tc).permit(:sentence, :sentence_order, :rank_of_importance, :company_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/t_cs_helper.rb
module TCsHelper
end

app/views/companies/_company_info.html.erb
<section id="company-info">
  <div id="company-logo">
    <%= link_to "http://#{@company.url}", target: "_blank" do %>
      <%= image_tag "logo/#{@company.logo}" %>
    <% end %>
  </div>
  <div id="company-desc">
    <h1><%= link_to "#{@company.name}", "http://#{@company.url}", target: "_blank" %></h1>
    <br><br>
    <p><%= @company.description %></p>
  </div>
</section>

app/views/companies/_important_terms.html.erb
<section id="important-terms">

  <div id="term-background"> 
    <div id="term-container">
      <div id="term-details">
        <div class="section-title">
          <h1> Most Important Terms</h1>
        </div>
        <table>
          <tbody>
              <tr>
                <th> Product/Service </th>
                <td> This is an example of a term in the terms and conditions that people deem important.</td>
              </tr>
              <tr>
                <th> Liability </th>
                <td> This is another example of a term in the terms and conditions that people deem important. </td>
              </tr>
              <tr>
                <th> Intellectual Property </th>
                <td> This is yet another example of a term that people deem important. </td>
              </tr>
              <tr>
                <th> Liability </th>
                <td> This is another example of a term in the terms and conditions that people deem important.</td>
              </tr>
              <tr>
                <th> Intellectual Property </th>
                <td> This is yet another example of a term that people deem important. This time it’s in a different category - intellectual property. </td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div id="participate">
    <h1> Data Analysis</h1>
    <h2>Company policy was last analyzed by ClearTerms on:</h2>
    <p>04/20/20</p>  <!-- arbitrary date- change later! -->
    <br>
    <h2>How the data was analyzed by ClearTerms:</h2>
    <p>Our method for analyzing websites uses a machine learning model that we built.
        This model is based on crowdsourced surveys that we conducted to capture people's
        opinion on various privacy statements. You can see more information about the logistics in the <%= link_to 'Frequently Asked Questions Page', faq_path %>.</p>
    <br>
    <h2>How does this work?</h2>
    <p> ClearTerms chooses these terms via a machine learning algorithm based on crowdsourcing. <br> <br> Hundreds of people identified 
        terms they thought were important; their opinions were tested for consistency and then used to train the model. </p>
    <br>
    <h2>Attribution</h2>
    <p> The company information on the page is powered by Crunchbase. Learn more about the company on the <%=  link_to "Crunchbase website", "#{@company.crunchbase_url}", target: "_blank" %>.</p>
    <br>
    <div class="d-flex justify-content-center">
      <%= link_to "Help Rank Terms & Conditions", help_path, class: "btn-get-started" %>
    </div>
    <br>
    <div class="d-flex justify-content-center">
      <%= link_to "Frequently Asked Questions", faq_path, class: "btn-get-started" %>
    </div>
  </div>

</section>

app/views/companies/_view_in_context.html.erb
<section id="view-in-context">
  <div id="term-content">
    <div class="section-title">
      <h1>View In Context</h1>
    </div>
    <br>
    <p> Here are a few examples: <br><br>
        The Intellectual Property disclosure will inform users that the contents, logo and other visual media you created is your property 
        and is protected by copyright laws. <br>

        <span class="emphasis">A Termination clause will inform that users' accounts on your website and mobile app or users' access to your 
        website and mobile (if users can't have an account with you) can be terminated in case of abuses or at your sole discretion. </span><br>

        A Governing Law will inform users which laws govern the agreement. This should the country in which your company is headquartered or 
        the country from which you operate your website and mobile app.<br>

        A Links To Other Web Sites clause will inform users that you are not responsible for any third party websites that you link to. 
        This kind of clause will generally inform users that they are responsible for reading and agreeing (or disagreeing) with the 
        Terms and Conditions or Privacy Policies of these third parties.<br>

        If your website or mobile app allows users to create content and make that content public to other users, a Content section will inform 
        users that they own the rights to the content they have created. <span class="emphasis">The "Content" clause usually mentions that 
        users must give you (the website or mobile app developer) a license so that you can share this content on your website/mobile app and to 
        make it available to other users.</span><br><br>

        Because the content created by users is public to other users, a DMCA notice clause (or Copyright Infringement ) section is 
        helpful to inform users and copyright authors that, if any content is found to be a copyright infringement, you will respond 
        to any DMCA takedown notices received and you will take down the content.<br><br>
              
        A Limit What Users Can Do clause can inform users that by agreeing to use your service, they're also agreeing to not do certain things. 
        This can be part of a very long and thorough list in your Terms and Conditions agreements so as to encompass the most amount of negative uses. </p>
  </div>
</section>

app/views/companies/index.html.erb
<section id="browse" class="browse section-bg2">
  <div class="container" data-aos="fade-in">
    <div class="section-title">
      <h3>Browse Companies</h3>
      <p>View terms & conditions from hundreds of ecommerce sites. Terms are ranked to show you what's most important.</p>
      <p><%= link_to "Can’t find the one you want?", add_company_path %></p>
    </div>
    <% count = 0%>
    <div class="row company-row d-flex align-items-stretch">
      <div class="company col-md-4">
        <% for company in Company.alphabetical %>
		  <% if count % 3 == 0%>
			</div>
			<div class="row company-row d-flex align-items-stretch">
		  <% end %>
		  <% count += 1 %>
		  <div class="company col-md-4">
            <%= link_to company_path(company) do %>
              <%= image_tag "logo/#{company.logo}", class: "mx-auto" %>
            <% end %>
		  </div>
	  <% end %>
    </div>
  </div>
</section>

app/views/companies/show.html.erb
<main id = "individual-company">
    <div class="container">
      <%= render partial: "company_info" %>
      <%= render partial: "important_terms" %>
      <%= render partial: "view_in_context" %>
      <br>
      <br>
      <br>
    </div>
</main>

app/views/home/_hero.html.erb
<section id="hero">

  <div class="container">
    <div class="row d-flex align-items-center">
      <div class="col-lg-6 py-5 py-lg-5 order-1 order-lg-1">
        <h1>We use machine learning model to read the T&C for you</h1>
        <h2>Nobody reads web site Terms & Conditions.<br>But they should.<span class="emphasis"> 91% of all users</span> consent without reading at all. The 9% who do read usually stop after the first paragraph.</h2>
        <h2>ClearTerms helps Internet users better understand the policies they are implicitly agreeing to <span class="emphasis">by highlighting the important ones for them.</span></h2>
        <br>
      </div>
      <div class="col-lg-6 px-5 order-2 order-lg-2 company-img">
        <%= image_tag 'logo/uniqlo.png', class: "hero-img" %>
        <%= image_tag 'logo/logitech.png', class: "hero-img" %>
        <%= image_tag 'logo/samsung.png', class: "hero-img" %>
        <%= image_tag 'logo/hp.png', class: "hero-img last" %>
        <br>
        <%= image_tag 'logo/sephora.png', class: "hero-img" %>
        <%= image_tag 'logo/farfetch.png', class: "hero-img" %>
        <%= image_tag 'logo/lululemon.png', class: "hero-img" %>
        <%= image_tag 'logo/apple.png', class: "hero-img last" %>
        <br>
        <br>
        <div class="d-flex justify-content-center">
          <%= link_to "More Companies", companies_path, class: "btn-get-started" %>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/home/_index_about.html.erb
<section id="about" class="about section-bg1">
  <div class="container">
    <div class="row">
      <div class="image col-xl-5 d-flex align-items-stretch justify-content-center justify-content-lg-start"></div>
      <div class="col-xl-7 pl-0 pl-lg-5 pr-lg-1 d-flex align-items-stretch">
        <div class="content d-flex flex-column">
          <h3>How does ClearTerms work?</h3>
          <div class="row">
            <div class="col-md-6">
              <!-- <i class="bx bx-receipt"></i> -->
              <h4>Pairwise comparison</h4>
              <p>Rather than asking volunteers to read entire documents and flag all of the important terms,
                <span class="emphasis">ClearTerms breaks the complex task into small parts;</span> individuals only need to compare two items at a time.</p>
            </div>
            <div class="col-md-6">
              <!-- <i class="bx bx-images"></i> -->
              <h4>Open definition of "importance"</h4>
              <p>Existing solutions use pre-defined criteria, which may innaccurately reflect what people really care about.</p>
               <p>We do not assume a priori what consumers find important. Instead, we let individuals define “importance” on their own terms - and it turns out that <span class="emphasis">people tend to agree.</span></p>
            </div>
          </div>
          <br>
          <div class="d-flex justify-content-center">
            <%= link_to "Frequently Asked Questions", faq_path, class: "btn-get-started" %>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>

app/views/home/_slider.html.erb
<section id="services" class="about section-bg2">
  <div class="container">
    <div class="row">
      <div class="col-xl-7 pl-0 pl-lg-5 pr-lg-1 d-flex align-items-stretch">
        <div class="content d-flex flex-column">
          <h3>Hundreds of ecommerce sites, with terms ranked by users like you.</h3>
        </div>
      </div>
    </div>
    <br>
    <div class="row centermode-slick">
      <div class="slick-item">
        <%= image_tag "logo/uniqlo.png" %>
      </div>
      <div class="slick-item">
        <%= image_tag "logo/facebook.png" %>
      </div>
      <div class="slick-item">
        <%= image_tag "logo/netflix.png" %>
      </div>
      <div class="slick-item">
        <%= image_tag "logo/away.png" %>
      </div>
      <div class="slick-item">
        <%= image_tag "logo/nike.png" %>
      </div>
      <div class="slick-item">
        <%= image_tag "logo/uo.png" %>
      </div>
    </div>
    <br>
    <br>
    <div class="d-flex justify-content-center">
      <%= link_to "Help Us Rank Terms & Conditions", help_path, class: "btn-get-started" %>
    </div>
    <br>
    <div class="d-flex justify-content-center">
      <%= link_to "Browse Companies", companies_path, class: "btn-get-started" %>
    </div>
  </div>
</section>

app/views/home/about.html.erb
<section id="about-us">
  <div id="team-info">
    <h3 data-aos="fade-in">About Us</h3>
    <br>
    <p> This project was led by <a href="http://www.cs.cmu.edu/~jasonh/" target="_blank">Jason Hong</a>. Annabel Sun and Bruce Xingyu Liu did the bulk of the work in developing
        the method, collecting data from the crowd, and analyzing the results. This web site was designed and built by Raymond Li, Wen Shan Jiang, and Stacy Kellner. </p>
    <p> There have also been many other students who have helped with data analysis or refining our models, including Angelia, Arpita Agrawal, Chaiwut Chaianuchittrakul, Lu Chen, Jonathan Dinu, Jineet Doshi, 
        Shawn Hanna, Brandon Jiang, Jennifer Kong, Siddharth Nair, Rajat Pandey, Alex Sciuto, Kunal Sekhri, Seoyeon Sim, Sarah Shy, Weijia Sun. </p>
    <p> This research was funded in part by the National Science Foundation (CNS-1422018). The views and conclusions contained in this web site
        are those of the authors and should not be interpreted as representing the official policies, either expressly or implied, of the National
        Science Foundation or the U.S. Government.</p>
    <br><br>
    <p>Have a question about ClearTerms? <a href="mailto:cleartermscontact@gmail.com">Contact Us.</a></p>
  </div>
</section>

app/views/home/add_company.html.erb
<section class="section section-bg1">
  <div class="container section-bg2" id="add-company">
    <div class="section-title">
      <br>
      <h3 data-aos="fade-in">Add a Company</h3>
    </div>
    <h4> Copy/paste the terms & conditions from any e-commerce* website. <br> We’ll show you the results. </h4>
    <br>
    <div id="add-company-desciption">
      <p>* <a href="https://en.wikipedia.org/wiki/E-commerce" class="link" target="_blank">E-commerce</a> is defined broadly as any website that sells products. </p>
      <p>Since the algorithm was made with e-commerce sites in mind, it works best on them. However, it will still yield results for other types of sites - try it out and 
      <a href="mailto:cleartermscontact@gmail.com">let us know</a> how it goes! </p>
      <div id="add-company-form">
        <textarea>paste the entire document...</textarea>
        <input type="submit" class="btn-submit" value="Test it!">
      </div>
    </div>
  </div> 
</section>

app/views/home/help.html.erb
<div class="container">
  <section class="section section-bg1">
    <div class="container section-bg2" id="crowd-inner">
      <div class="section-title">
        <br><br><br>
        <h3 data-aos="fade-in">Participate</h3>
        <p>Help us improve our ML model by ranking some terms & conditions.</p><br><br>
        <p>Click the statement that you think is more important for you, 
            a customer browsing the website, to know.</p>
        <br>
        <p> The following two terms&conditions are from: 
            https://www.geekbuying.com/help/customer_service/return_policy</p>
        <br>
        <div class="row">
          <div class="statement left" id="s-left" onclick="selectStatementLeft()"> 
            <h4 class="statement-title"> Statement 1: </h4>
            <p class="statement-description">
              GeekBuying will be in charge of all the repair handling
              fees and non-artificial defective component replacement
              charges (this free repair rule does not apply to
              motherboard & screen).</p>
          </div>
          <div class="statement right" id="s-right" onclick="selectStatementRight()"> 
            <h4 class="statement-title"> Statement 2: </h4>
              <p class="statement-description">
                Geekbuying sincerely suggests every respected customer
                to read the following regulations carefully 
                before purchase.</p>
          </div>
        </div>
        <div class="statement-equal" id="s-bot" onclick="selectStatementBot()"> 
          <p class="statement-description">Both statements are equally important.</p>
        </div>
        <input type="submit" class="btn-submit" id="s-submit" value="Submit">
      </div>
    </div>
  </section>
</div>

app/views/home/index.html.erb
<%= render partial: "hero" %>

  <main id="main">
    <%= render partial: "index_about" %>
    <%= render partial: "slider" %>
  </main>

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClearTerms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'application', 'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css' %>
    <%= stylesheet_link_tag    'application', 'https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'application', 'https://kit.fontawesome.com/18834a1269.js' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= render :partial => "partials/nav" %>
    <%= yield %>
    <%= render :partial => "partials/footer" %> 
  </body>
</html>

app/views/partials/_footer.html.erb
<footer id="footer">
  <div class="container footer-top">
    <div class="row justify-content-left">
      <div class="col-lg-4">
        <h3>ClearTerms</h3>
        <br>
        <div><%= link_to 'Contact Us', about_path %></div>
        <div><%= link_to 'Frequently Asked Questions', faq_path %></div>
        <div><%= link_to 'Help Us', help_path %></div>
        <div><a href="http://3.210.81.13/about_us">CHIMPS Lab</a></div>
      </div>
    </div>
  </div>
  <div class="container footer-bottom clearfix">
    <div class="copyright">
        <!-- &copy; Copyright <strong><span>ClearTerms</span></strong>. All Rights Reserved -->
    </div>
  </div>
</footer>

app/views/partials/_nav.html.erb
<header id="header">
  <div class="container d-flex">
    <div class="logo mr-auto">
        <h1 class="text-light"><%= link_to 'ClearTerms', home_path %><span></span></h1>
        <h6>simplifying terms & conditions</h6>
    </div>
    <nav class="nav-menu d-none d-lg-block float-right">
      <ul>
        <li><%= link_to 'Browse Companies', companies_path %></li>
        <li><%= link_to 'FAQ', faq_path %></li>
        <li><%= link_to 'Help Us', help_path %></li>
        <li><%= link_to 'About Us', about_path %></li>
        <li class="col-xs-3">
            <div class="input-group mb-3" >
                <input class="form-control input-search" type="text" placeholder="find a company..." id="myInput">
                <div class="input-group-append">
                  <button href="browse.html" class="btn btn-search" type="submit"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </li>
      </ul>
    </nav>
  </div>            
</header>